### ISSUE TITLE
add a missing restaurant

### ISSUE THREAD

**Issue by 0xadada** [unredacted-word/katamari-restaurants#5]
add a missing closed boston/cambridge or somerville restaurant.

NO JAMAICA PLAIN!

**Comment by 0xadada** [comment]
j/k about Jamaica Plain.

**Comment by ywalia01** [comment]
Hey, I'd like to work on this. Could your provide some more details
Thanks

**Comment by 0xadada** [comment]
Many resturants in Boston, Cambridge and Somerville, Massachusetts, USA are closing due to COVID-19. This site lists the closed restaurants, with a URL link to their closing statement and m with a quote about why they closed. 

If you find one, you can add it to `https://github.com/unredacted-word/katamari-restaurants/blob/master/_data/companies.yml`, following that yaml format.

**Comment by ywalia01** [comment]
Alright. Do you have a good source for this?

**Comment by 0xadada** [comment]
> Alright. Do you have a good source for this?

https://bostonrestaurants.blogspot.com/

**Comment by ywalia01** [comment]
Thanks

**Comment by AgaskarJ** [comment]
I'm in the Boston area, would love to add to the list

**Comment by 0xadada** [comment]
fixed with https://github.com/unredacted-word/katamari-restaurants/pull/6

**Comment by 0xadada** [comment]
thanks @AgaskarJ. I also went to Northeastern (graduated in 2004) and i used to visit Connor Larkins quite often 😭

**Comment by AgaskarJ** [comment]
@0xadada that's awesome! Yeah very sad about them having to close down :( I'm not sure if Rebecca's cafe was there when you were at Northeastern, but they also closed

**Comment by 0xadada** [comment]
@AgaskarJ I only hope Chicken Lous is still open. I loved that place. It had shitty hours, but it was so good. I rode my bike over there back in February from Somerville during lunch and had some. Amazing.

**Comment by AgaskarJ** [comment]
@0xadada OH damn, I totally forgot but unfortunately Chicken Lous is closed too. But it closed because the owner retired. I agree though their sandwiches were amazing

**Comment by 0xadada** [comment]
> @0xadada OH damn, I totally forgot but unfortunately Chicken Lous is closed too. But it closed because the owner retired. I agree though their sandwiches were amazing

I just read the article about their closing. Just when i thought 2020 couldn't get any worse... 😭
